# filebeat/filebeat.yml
filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  
  - decode_json_fields:
      fields: ["message"]
      target: "json"
      
  # - drop_event:
  #     when:
  #       not:
  #         contains:
  #           container.name: "analytics"

output.logstash:
  hosts: ["logstash:5044"]