version: '3.8'

services:
  analytics:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=${DB_NAME}
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=${ENVIRONMENT}

  redis:
    image: "redis:6.2-alpine"
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A tasks worker --queues=sync --loglevel=debug
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=${DB_NAME}
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=${ENVIRONMENT}

  celery_beat:
    build: .
    command: celery -A tasks beat --loglevel=debug
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=${DB_NAME}
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=${ENVIRONMENT}